### ISSUE TITLE
module version

### ISSUE THREAD

**Issue by mrcomac** [CelestianGC/osric-compendium#3]
is the version of the module correct? it shows `` "version": "2023.05.29"``

**Comment by 69bossmustang** [comment]
> is the version of the module correct? it shows ` "version": "2023.05.29"`

Where are you seeing that? The version that is current is version": "2023.12.18",

**Comment by amir-arad** [comment]
the source is not up to date. the December release was not pushed to github @EOTB1E

**Comment by 69bossmustang** [comment]
> the source is not up to date. the December release was not pushed to github @EOTB1E

The release was which is the part that is where Foundry gets it for install.  If you mean the source campaign he built the compendium with, it's no longer going to reside here. The binary files are to large (GitHub wont accept them).
