### ISSUE TITLE
Character Class Items Locked

### ISSUE THREAD

**Issue by jbronner1972** [CelestianGC/osric-compendium#4]
Foundry Version 11.315
ARS Version 2024.04.31
OSRIC Compendium Version 2024.04.31

OSRIC Items (PC) / Classes are locked and not viewable/editable in the compendia, after import in Items, or on the character sheets. 
![Untitled1](https://github.com/CelestianGC/osric-compendium/assets/10430565/3d6c8a0e-2c74-4dc0-8e3c-f57f90efc8e3)
![Untitled2](https://github.com/CelestianGC/osric-compendium/assets/10430565/9c1bee7c-7097-4c0f-86c5-5ca440ce3760)

Clicking on the Character Class item yields nothing.

**Comment by jbronner1972** [comment]
Here is the console dump for the error.

![Untitled](https://github.com/CelestianGC/osric-compendium/assets/10430565/7b4fc906-21b7-40c5-8e17-d4c7a06bfdb9)

**Comment by 69bossmustang** [comment]
This is related to the migration from #select to selectOptions from previous update. Found the cause and fixed and will submit update. This isnt related to the OSRIC compendium however, it's the ruleset.
